name: Track Netlify Deploy

on:
  push:
    branches: [master]

jobs:
  track-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for Netlify deploy
        uses: probots-io/wait-for-netlify-action@v1
        with:
          site_id: "0f75e710-16ce-4ef5-a7b1-a449b640594a"
          max_timeout: 300
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
